"""
Data models for Haytham startup accelerator system.

This module defines all dataclasses used throughout the system to represent
startup specifications, market research, personas, business models, and more.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Optional

# ============================================================================
# Core Startup Specification
# ============================================================================


@dataclass
class StartupSpecification:
    """Complete startup specification generated by Haytham"""

    project_name: str
    input_type: str  # "idea" or "poc"
    concept_summary: str  # Problem, opportunity, solution
    code_analysis: Optional["CodeAnalysis"]  # Only for POC workflow
    market_research: "MarketResearch"
    target_personas: list["Persona"]
    product_definition: "ProductDefinition"
    business_model: "BusinessModel"
    unique_value_proposition: str
    mvp_specification: "MVPSpec"
    assumptions: list["Assumption"]
    risks: list["Risk"]
    scalability_plan: Optional["ScalabilityPlan"]  # For POC + later bootstrapping
    validation_status: "ValidationResult"
    learning_insights: list["LearningInsight"] | None = None  # Structured captured insights
    quality_metrics: Optional["QualityMetrics"] = None  # Evaluation metrics
    generated_at: datetime = field(default_factory=datetime.now)


# ============================================================================
# Learning and Quality Metrics
# ============================================================================


@dataclass
class LearningInsight:
    """Captured insight for system-level improvement"""

    insight: str
    context: str
    source_agent: str
    confidence: float  # 0-100 (percentage)
    impact: str  # "low", "medium", "high"
    timestamp: datetime = field(default_factory=datetime.now)
    validated: bool = False  # Set to True when validated by real-world outcomes


@dataclass
class QualityMetrics:
    """Evaluation and learning metrics for the specification"""

    validation_accuracy: float  # % verified insights (0-100)
    plan_quality_score: float  # Weighted average of section confidences (0-100)
    iteration_delta: float | None  # Quality change vs. previous run
    time_to_plan: float  # End-to-end runtime in seconds
    learning_yield: int  # Number of reusable insights captured
    agent_confidences: dict[str, float]  # Per-agent confidence scores


# ============================================================================
# Code Analysis (POC Transformation)
# ============================================================================


@dataclass
class CodeAnalysis:
    """Analysis of existing POC codebase"""

    structure: dict[str, Any]  # Directory structure
    tech_stack: list[str]  # Technologies used
    features: list[str]  # Implemented features
    dependencies: list[str]  # Dependencies
    quality_score: float  # 0-100
    strengths: list[str]
    improvement_areas: list[str]


# ============================================================================
# Growth and Scaling
# ============================================================================


@dataclass
class RoadmapMilestone:
    """Product roadmap milestone"""

    phase: str  # "MVP", "Growth", "Scale"
    timeline: str
    objectives: list[str]
    deliverables: list[str]
    success_criteria: list[str]


@dataclass
class GTMStrategy:
    """Go-to-market strategy"""

    target_segments: list[str]
    channels: list[str]
    messaging: str
    pricing_strategy: str
    launch_plan: list[str]


@dataclass
class ScalabilityPlan:
    """Growth and scaling plan"""

    roadmap: list[RoadmapMilestone]
    gtm_strategy: GTMStrategy
    scaling_metrics: list[str]
    funding_needs: str | None
    technical_scaling: list[str]
    business_scaling: list[str]


# ============================================================================
# Market Research
# ============================================================================


@dataclass
class Competitor:
    """Competitor information"""

    name: str
    description: str
    strengths: list[str]
    weaknesses: list[str]
    market_position: str


@dataclass
class MarketResearch:
    """Market and competitor analysis results"""

    market_size: str
    growth_rate: str
    key_trends: list[str]
    competitors: list[Competitor]
    opportunities: list[str]
    threats: list[str]


# ============================================================================
# Product Strategy
# ============================================================================


@dataclass
class Persona:
    """User persona definition"""

    name: str
    role: str
    demographics: dict[str, str]
    pain_points: list[str]
    motivations: list[str]
    behaviors: list[str]
    goals: list[str]


@dataclass
class Feature:
    """Product feature specification"""

    name: str
    description: str
    priority: str  # "must-have", "should-have", "nice-to-have"
    user_value: str


@dataclass
class UserJourney:
    """User journey through the product"""

    persona: str
    steps: list[str]
    touchpoints: list[str]
    pain_points: list[str]


@dataclass
class ProductDefinition:
    """Product concept and core functionality"""

    concept: str
    core_features: list[Feature]
    user_journeys: list[UserJourney]
    technical_requirements: list[str]


# ============================================================================
# Business Model
# ============================================================================


@dataclass
class RevenueStream:
    """Revenue stream definition"""

    source: str
    description: str
    pricing_model: str
    projected_revenue: str | None = None


@dataclass
class BusinessModel:
    """Business model and monetization strategy"""

    revenue_streams: list[RevenueStream]
    pricing_model: str
    cost_structure: list[str]
    key_metrics: list[str]


# ============================================================================
# MVP Specification
# ============================================================================


@dataclass
class MVPSpec:
    """Minimum Viable Product specification"""

    core_features: list[Feature]
    timeline: str
    success_criteria: list[str]
    technical_stack: list[str]


# ============================================================================
# Assumptions and Risks
# ============================================================================


@dataclass
class Assumption:
    """Key assumption that needs validation"""

    description: str
    category: str  # "market", "technical", "business"
    criticality: str  # "low", "medium", "high"
    validation_method: str


@dataclass
class Risk:
    """Identified risk and mitigation"""

    category: str  # "technical", "market", "operational", "regulatory"
    description: str
    likelihood: str  # "low", "medium", "high"
    impact: str  # "low", "medium", "high"
    mitigation: str


# ============================================================================
# Validation
# ============================================================================


@dataclass
class ValidationIssue:
    """Specific validation issue found"""

    claim: str  # The claim being questioned
    section: str  # Which section it's from
    severity: str  # "low", "medium", "high", "critical"
    reason: str  # Why it's flagged
    suggested_fix: str | None = None


@dataclass
class ValidationResult:
    """Comprehensive fact-checking and validation results"""

    is_valid: bool  # True only if confidence > 80%
    confidence_score: float  # 0-100 (overall validation confidence)
    claims_checked: int  # Total number of claims validated
    claims_verified: int  # Number of claims successfully verified
    claims_flagged: int  # Number of suspicious/unverified claims
    issues_found: list[ValidationIssue]
    recommendations: list[str]
    sources_consulted: list[str]  # Sources used for fact-checking
